<?php
return [
    'GET' => [
        '/' => 'PageController@home',
        '/destination' => 'PageController@destination',
        '/destination/details' => 'PageController@destinationDetails',
        '/packages' => 'PageController@packages',
        '/payment' => 'PageController@payment',
        '/about' => 'PageController@about',
        '/help' => 'PageController@help',
        '/read-more' => 'PageController@readMore',
        '/login' => 'AuthController@loginAction',
        '/register' => 'AuthController@registerAction',
        '/logout' => 'AuthController@logoutAction',
        '/dashboard' => 'DashboardController@indexAction',
        '/bookings' => 'BookingController@indexAction',
        '/bookings/create' => 'BookingController@createAction',
        '/bookings/edit' => 'BookingController@editAction',
        '/admin/discounts' => 'AdminController@discountsAction',
        '/admin/packages' => 'PackageController@adminIndex',
        '/admin/packages/create' => 'PackageController@showCreate',
        '/admin/packages/edit' => 'PackageController@showEdit',
        '/admin/destinations' => 'DestinationController@adminIndex',
        '/admin/destinations/create' => 'DestinationController@showCreate',
        '/admin/destinations/edit' => 'DestinationController@showEdit',
        '/admin/bookings' => 'AdminController@bookingsAction',
        '/admin/bookings/view' => 'AdminController@viewBookingAction',
        '/admin/dashboard' => 'AdminController@dashboardAction',
        '/api/check-login' => 'ApiController@checkLogin',
        '/api/destinations' => 'ApiController@listDestinations',
        '/api/destinations/detail' => 'ApiController@getDestination',
        '/api/packages' => 'ApiController@listPackages',
        '/api/loyalty-discount' => 'ApiController@getLoyaltyDiscount',
        '/api/next-tier' => 'ApiController@getNextTier',
    ],
    'POST' => [
        '/login' => 'AuthController@loginAction',
        '/register' => 'AuthController@registerAction',
        '/bookings/create' => 'BookingController@createAction',
        '/bookings/delete' => 'BookingController@deleteAction',
        '/bookings/edit' => 'BookingController@editAction',
        '/admin/destinations/create' => 'DestinationController@create',
        '/admin/destinations/edit' => 'DestinationController@update',
        '/admin/destinations/delete' => 'DestinationController@delete',
        '/admin/packages/create' => 'PackageController@create',
        '/admin/packages/edit' => 'PackageController@update',
        '/admin/packages/delete' => 'PackageController@delete',
        '/admin/discounts' => 'AdminController@discountsAction',
        '/admin/bookings' => 'AdminController@bookingsAction',
        '/api/save-booking' => 'ApiController@saveBooking',
    ],
];
